[target.aarch64-unknown-linux-musl]
linker = "clang"

[target.x86_64-unknown-linux-musl]
linker = "clang"

[env]
EXT_PHP_RS_ALLOWED_BINDINGS = "PHP_INFO_ALL,PHP_INFO_CREDITS,PHP_VERSION,module_registry,php_handle_aborted_connection,php_handle_auth_data,php_output_end_all,php_print_info,php_register_variable,php_tsrm_startup_ex,zend_error,zend_extension,zend_extensions,zend_shutdown_strtod,zend_update_current_locale"
