[target.'cfg(not(target_os = "windows"))']
rustflags = ["-C", "link-arg=-Wl,-undefined,dynamic_lookup"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.i686-pc-windows-msvc]
linker = "rust-lld"

[env]
EXT_PHP_RS_ALLOWED_BINDINGS = "php_register_variable,php_handle_auth_data,php_handle_aborted_connection"
